services:

  postgres:
    image: postgres:16
    container_name: aurora-postgres

    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aurora-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: